repos:
  - repo: local
    hooks:
      - id: shrimport
        name: Shrimport (local)
        entry: python -m main
        language: python
        additional_dependencies: [ libcst>=1.0.0 ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        types: [ python ]
      - id: end-of-file-fixer
        types: [ python ]
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        types: [ python ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile=black"]

  - repo: https://github.com/psf/black
    rev: '25.1.0'
    hooks:
      - id: black
        types: [ python ]
        args: [ -l, '100' ]
